---
title: Додавання звуку з бібліотеки
hero_image: images / banner.png
description: Як додати звук до вашого Scratch sprite
original_url:
theme: cc-прототип
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "подряпати"
steps:
  - 
    title: Додайте звук у свій спрайт
