---
title: Een geluid uit de bibliotheek toevoegen
hero_image: images / banner.png
description: Hoe voeg je een geluid aan je Scratch-sprite
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Voeg een geluid toe aan je sprite
