---
title: Thêm âm thanh từ thư viện
hero_image: images / banner.png
description: Cách thêm âm thanh vào sprite Scratch của bạn
original_url:
theme: nguyên mẫu cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "vết trầy"
steps:
  - 
    title: Thêm âm thanh vào sprite của bạn
