---
title: Dodavanje zvuka iz knjižnice
hero_image: images/banner.png
description: Kako dodati zvuk Scratch liku
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj zvuk liku
