---
title: Dodavanje zvuka iz biblioteke
hero_image: slike / banner.png
description: Kako dodati zvuk Scratch spriteu
original_url: ""
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "ogrepsti"
steps:
  - 
    title: Dodajte zvuk na svoj sprite
