---
title: Dodavanje zvuka iz knjižnice
hero_image: images/banner.png
description: Kako dodati zvuk Scratch liku
original_url: ""
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Scratch"
steps:
  - 
    title: Dodajte liku zvuk
