---
title: Ychwanegu sain o'r llyfrgell
hero_image: images/banner.png
description: Sut i ychwanegu sain at dy giplun Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ychwanegu sain at dy giplun
