---
title: Hinzufügen von einem Klang aus der Bibliothek
hero_image: images/banner.png
description: So wird ein Klang zu deiner Scratch-Figur hinzugefügt
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Füge deiner Figur einen Klang hinzu
