---
title: Adăugarea unui sunet din bibliotecă
hero_image: images / banner.png
description: Cum de a adăuga un sunet la sprite Scratch
original_url: ""
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Adăugați un sunet la sprite
