---
title: Adicionando um som da biblioteca
hero_image: images/banner.png
description: Como adicionar um som para o seu ator Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Adicione um som para o seu ator
