---
title: Adicionando um som da biblioteca
hero_image: images/banner.png
description: Como adicionar um som ao seu sprite Scratch
original_url:
theme: protótipo cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "coçar, arranhão"
steps:
  - 
    title: Adicione um som à sua sprite
