---
title: Menambahkan suara dari perpustakaan
hero_image: gambar / banner.png
description: Cara menambahkan suara ke Scratch sprite Anda
original_url: ""
theme: cc-prototipe
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "menggaruk"
steps:
  - 
    title: Tambahkan suara ke sprite Anda
