---
title: Menambahkan sebuah suara dari pustaka
hero_image: images/banner.png
description: Cara menambahkan suara ke sprite Scratch Kamu
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - title: Menambahkan sebuah suara ke sprite Kamu
