---
title: Dodajanje zvoka iz knjižnice
hero_image: images / banner.png
description: Kako dodati zvok v Scratch sprite
original_url:
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "praska"
steps:
  - 
    title: Dodajte zvok vašemu sprite
