---
title: Pridanie zvuku z knižnice
hero_image: images / banner.png
description: Ako pridať zvuk Scratch sprite
original_url:
theme: cc-prototyp
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "škrabanec"
steps:
  - 
    title: Pridajte zvuk k vášmu sprite
