---
title: Menambah bunyi dari perpustakaan
hero_image: imej / banner.png
description: Bagaimana untuk menambah bunyi untuk engkol Scratch anda
original_url:
theme: prototaip cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "awal"
steps:
  - 
    title: Tambah bunyi untuk sprite anda
