---
title: Προσθέτοντας ένα ήχο από τη βιβλιοθήκη
hero_image: images/banner.png
description: Πώς να προσθέσεις έναν ήχο στο αντικείμενο Scratch
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Πρόσθεσε έναν ήχο στο αντικείμενό σου
