---
title: Dodavanje zvuka iz biblioteke
hero_image: images/banner.png
description: Kako da dodaš zvuk svom Scratch liku
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj zvuk svom liku
