---
title: Ajouter un son depuis la bibliothèque
hero_image: images / banner.png
description: Comment ajouter un son à votre lutin de Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ajouter un son à votre lutin
