---
title: Aggiungere un suono dalla libreria
hero_image: images/banner.png
description: Come aggiungere un suono al tuo sprite di Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Aggiungi un suono al tuo sprite
